### ISSUE TITLE
Add new AWS region eu-central-1 (Frankfurt)

### ISSUE THREAD

**Issue by thomas-riccardi** [turnkeylinux/aws-datacenters#4]
A new AWS region was added in october 2014, could you please add this ?

See http://aws.amazon.com/about-aws/whats-new/2014/10/23/announcing-the-aws-eu-frankfurt-region/

**Comment by grzegorz-dubicki** [comment]
+1

**Comment by Lax** [comment]
+1

**Comment by fox91** [comment]
+1

**Comment by alonswartz** [comment]
Thanks to everyone for showing their support for this. We've targeted support for the 13.1 milestone release, which will include building the appliance images in the new region, adding support to the TurnKey Hub and TKLBAM, and of course updating the aws-datacenters mapping with #5 by @Lax

**Comment by sandstrom** [comment]
Great!

**Comment by redburn** [comment]
+1

The India and US East (Ohio) regions have also launched since then.

**Comment by dprestegard** [comment]
Any word on adding the latest AWS regions??

**Comment by JedMeister** [comment]
This should now be closed via https://github.com/turnkeylinux/aws-datacenters/pull/11/commits/865681e8457ce43110bd21f4777110e2f3d326fb

If/when we next get out of sync I'll aim to be more responsive to contributions...
